service: ebs-backup 

frameworkVersion: ">=1.12.0"

provider:
  name: aws
  runtime: nodejs6.10
  stage: dev
  region: ap-northeast-1
  cfLogs: true

# you can add statements to the Lambda function's IAM Role here
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "ec2:DescribeInstances"
        - "ec2:DescribeSnapshots"
        - "ec2:CreateSnapshot"
        - "ec2:DeleteSnapshot"
      Resource:
        - "*"
    - Effect: "Allow"
      Action:
        - "ec2:CreateTags"
      Resource:
        - "arn:aws:ec2:ap-northeast-1::snapshot/*"

functions:
  ebsBackup:
    handler: ebs-backup/handler.backup
    description: daily ebs backup
    memorySize: 256
    timeout: 300
    events:
      # 04:00 JSTに実行されます。
      - schedule:
          name: ebs-backup
          description: 'daily ebs backup'
          rate: cron(0 19 ? * * *)
